const validationErrors = {
     PASSWORD_TOO_SHORT: "Password should be at least 8 characters",
     PHONENUMBER_TOO_SHORT : "PhoneNumber should be at least 10 number",
     PASSWORD_MISMATCH: "Password and ConfirmPassword do not match",
     INVALID_EMAIL: "Please enter a valid email address",
     USER_ALREADY_REGISTERED: "User is already registered",
     OTP_ERROR: "Error sending email",
     INVALID_OTP: "Invalid OTP",
     OTP_EXPIRED: "OTP has expired",
     INTERNAL_SERVER_ERROR: "Internal Server Error",
     OTP_SENT: "OTP sent to your email",
     USER_NOT_REGISTERED: "User not registered",
     INCORRECT_PASSWORD: "Password is incorrect",
     USER_NOT_FOUND: "User not found",
     EMAIL_ALREADY_REGISTERED: "This email is already registered",
     UNKNOWN_STAFF: "Staff not found",
     REGISTERED_SUCCESSFULLY: "Registered successfully",
     ACCESS_DATA_SUCCESSFULLY: "Successfully access all data",
     DATA_UPDATED: "Data id updated",
     UPDATED_RECORD: "updated record",
     DATA_UPDATE_SUCCESSFULLY: "Update data successfully",
     DELETED_SUCCESSFULLY: "Student deleted successfully",
     LOGIN_SUCCESSFULLY: "Login successfully",
     INVALID_TOKEN: "Invalid token",
     NO_TOKEN_PROVIDED: "No token provided",
     PASSWORD_CHANGE: "Password changes successfully",
     ERROR: "An error occurred while changing the password",
     PROFILE_UPDATED: "Profile is updated successfully",
     PLEASE_ENTER_ALL_FIELD: "Please enter all the fields",
     ROLLNUMBER_ALREADY_EXIST : "Roll Number already exsited",
     STAFF_EMAIL_ALREADY_EXIST : "Staff email already register",
    STAFF_ALLREADY_REGISTER : "Staff is already register",
    STAFF_DELETED : "Staff deleted successfully ",
    STATUS_NOT_MATCH: "Student is not register or status not match",
   
 };        
 
 export default validationErrors;